### ISSUE TITLE
Nothing happens when "add playlist"

### ISSUE THREAD

**Issue by mappers653** [kamilkosek/jellyplist#11]
1. Press add play list
2. list gets added to monitored and list gets added with tags to jellyfin
3. tracks gets download, playlist all in green but still no tracks in the playlist in Jellyfin
4. green button "add to my jellyfin" green despite clicking on it and error in log 
```dockerfile
jellyplist           | [2024-11-24 16:18:23,383] ERROR in app: Exception on /addplaylist [POST]
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
jellyplist           |     response = self.full_dispatch_request()
jellyplist           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
jellyplist           |     return self.finalize_request(rv)
jellyplist           |            ^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
jellyplist           |     response = self.make_response(rv)
jellyplist           |                ^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1212, in make_response
jellyplist           |     raise TypeError(
jellyplist           | TypeError: The view function for 'add_playlist' did not return a valid response. The function either returned None or ended without a return statement.
``` 

same behavior with additional added playlist, only worked properly once on the first try

**Comment by vergemarie** [comment]
same error here

**Comment by kamilkosek** [comment]
Could you please do the following: 
add `LOG_LEVEL = DEBUG` and `REFRESH_LIBRARIES_AFTER_DOWNLOAD_TASK = true` to your `.env` File.
Change the image tags on all Jellyplist conaitners to `dev`
Add a Playlist, go to `Admin-> Tasks` and run the `download` task, wait for it for finish. Then run `update_all_playlists_track_status` wait for it to finish and last but not least run the `update_jellyfin_id_for_downloaded_tracks` task.
provide the logs from `jellyplist-worker` as well as `jellyplist`

**Comment by mappers653** [comment]
1. change tag to dev
2. press add playlist
```
HTTPSConnectionPool(host='i.scdn.co', port=443): Max retries exceeded with url: /image/ab67706f000000023ed5d7cbbf2b72b1cee1957c (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused')) 
``` 
task 1 to 5 complete 

```dockerfile
jellyplist           | [2024-11-26 11:09:12,748][         client.py: 184 -        get_playlists() ]   DEBUG - Url=http://privateip:port/Items
jellyplist           | [2024-11-26 11:09:12,825][         client.py: 187 -        get_playlists() ]   DEBUG - Response = 200
jellyplist           | [2024-11-26 11:09:39,225][         client.py: 126 - get_playlist_metadata() ]   DEBUG - Url=http://privateip:port/Items/406389ceb45038720032153fcd23f801
jellyplist           | [2024-11-26 11:09:39,232][         client.py: 129 - get_playlist_metadata() ]   DEBUG - Response = 200
jellyplist           | [2024-11-26 11:09:39,232][         client.py: 161 - update_playlist_metadata() ]   DEBUG - Url=http://privateip:port/Items/406389ceb45038720032153fcd23f801
jellyplist           | [2024-11-26 11:09:39,235][         client.py: 164 - update_playlist_metadata() ]   DEBUG - Response = 204
``` 

```dockerfile
jellyplist           | [2024-11-26 11:11:33,893][         client.py: 184 -        get_playlists() ]   DEBUG - Url=http://privateip:port/Items
jellyplist           | [2024-11-26 11:11:33,937][         client.py: 187 -        get_playlists() ]   DEBUG - Response = 200
jellyplist           | [2024-11-26 11:11:51,125][         client.py: 184 -        get_playlists() ]   DEBUG - Url=http://privateip:port/Items
jellyplist           | [2024-11-26 11:11:51,184][         client.py: 187 -        get_playlists() ]   DEBUG - Response = 200
jellyplist           | [2024-11-26 11:12:09,217][         client.py: 184 -        get_playlists() ]   DEBUG - Url=http://privateip:port/Items
jellyplist           | [2024-11-26 11:12:09,266][         client.py: 187 -        get_playlists() ]   DEBUG - Response = 200
``` 
no error detected in the worker log

**Comment by kamilkosek** [comment]
@mappers653  unfortunately you´re hitting a API rate limit from spotify while downloading the cover images. 
I should implement caching on the image endpoints to mitigate this issue.

**Comment by kamilkosek** [comment]
I just published a new dev build, could you try it ?

**Comment by mappers653** [comment]
I started a fresh instance of jellyfin but now we have this issue with the spotify api, everthing results in Internal Server Error so standing by to continue testing

**Comment by kamilkosek** [comment]
Hi, another release with reworked Spotify api implementation is out, could you test it ?
