### ISSUE TITLE
Download Task Failing, Does Not Continue

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#20]
When downloading playlists, the following error is encountered:

```
[2024-11-26 20:05:25,511: WARNING/ForkPoolWorker-15] [2024-11-26 20:05:25,511] INFO in tasks: Searching for track in Jellyfin: wii u mii maker ☆!!
[2024-11-26 20:05:25,511: INFO/ForkPoolWorker-15] Searching for track in Jellyfin: wii u mii maker ☆!!
[2024-11-26 20:05:25,568: ERROR/ForkPoolWorker-15] HTTP Error for GET to https://api.spotify.com/v1/tracks/7e9ZRzvr5FN6EliqURdTzV with Params: {'market': None} returned 404 due to Resource not found
[2024-11-26 20:05:25,568: WARNING/ForkPoolWorker-15] [2024-11-26 20:05:25,568] ERROR in functions: Error fetching track 7e9ZRzvr5FN6EliqURdTzV from Spotify: http status: 404, code:-1 - https://api.spotify.com/v1/tracks/7e9ZRzvr5FN6EliqURdTzV:
 Resource not found, reason: None
[2024-11-26 20:05:25,568: ERROR/ForkPoolWorker-15] Error fetching track 7e9ZRzvr5FN6EliqURdTzV from Spotify: http status: 404, code:-1 - https://api.spotify.com/v1/tracks/7e9ZRzvr5FN6EliqURdTzV:
 Resource not found, reason: None
[2024-11-26 20:05:25,576: ERROR/ForkPoolWorker-15] Task app.tasks.download_missing_tracks[3428f290-188d-4497-93da-60f082ade384] raised unexpected: AttributeError("'NoneType' object has no attribute 'get'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/tasks.py", line 112, in download_missing_tracks
    preview_url = spotify_track.get('preview_url')
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

This terminates the download task and no other songs are attempted to be downloaded.

The API call in the above example gives the following output:

```
error	
status	401
message	"No token provided"
```

The Spotify client id/secret are included in the .env, not sure if that's what it's referring to by "No token provided". Is it possible that the program is being rate-limited somehow?

**Comment by NovaCyntax** [comment]
Re-ran to get a more verbose log output for you.

```
[2024-11-27 05:04:49,150][          tasks.py: 108 - download_missing_tracks() ]    INFO - Processing track: wii u mii maker ☆!! [7e9ZRzvr5FN6EliqURdTzV]
[2024-11-27 05:04:49,150][          tasks.py: 114 - download_missing_tracks() ]    INFO - Searching for track in Jellyfin: wii u mii maker ☆!!
[2024-11-27 05:04:49,313][         client.py: 292 -          _internal_call() ]   ERROR - HTTP Error for GET to https://api.spotify.com/v1/tracks/7e9ZRzvr5FN6EliqURdTzV with Params: {'market': None} returned 404 due to Resource not found
[2024-11-27 05:04:49,313][      functions.py: 150 - get_cached_spotify_track() ]   ERROR - Error fetching track 7e9ZRzvr5FN6EliqURdTzV from Spotify: http status: 404, code:-1 - https://api.spotify.com/v1/tracks/7e9ZRzvr5FN6EliqURdTzV:
 Resource not found, reason: None
[2024-11-27 05:04:49,314][          tasks.py: 411 - find_best_match_from_jellyfin() ]   DEBUG - Trying to find best match from Jellyfin server for track: wii u mii maker ☆!!
[2024-11-27 05:04:49,314][         client.py: 244 -     search_music_tracks() ]   DEBUG - Url=http://192.168.1.14:8096/Items
[2024-11-27 05:04:50,085][         client.py: 248 -     search_music_tracks() ]   DEBUG - Response = 200
[2024-11-27 05:04:50,087][         client.py: 199 -           get_libraries() ]   DEBUG - Url=http://192.168.1.14:8096/Library/VirtualFolders
[2024-11-27 05:04:50,092][         client.py: 202 -           get_libraries() ]   DEBUG - Response = 200
1:M 27 Nov 2024 05:04:50.093 * 100 changes in 300 seconds. Saving...
[2024-11-27 05:04:50,092][         client.py: 219 -         refresh_library() ]   DEBUG - Url=http://192.168.1.14:8096/Items/7e64e319657a9516ec78490da03edccb/Refresh
[2024-11-27 05:04:50,095][         client.py: 222 -         refresh_library() ]   DEBUG - Response = 204
[2024-11-27 05:04:50,099][          trace.py: 267 -              _log_error() ]   ERROR - Task app.tasks.download_missing_tracks[5f9931c5-a9b3-4c34-8344-ec623e056f01] raised unexpected: AttributeError("'NoneType' object has no attribute 'get'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/tasks.py", line 131, in download_missing_tracks
    preview_url = spotify_track.get('preview_url')
                  ^^^^^^^^^^^^^^^^^
```

**Comment by kamilkosek** [comment]
I just published a new dev build, could you try it ?

**Comment by NovaCyntax** [comment]
10 minutes in and it appears to be working for downloads, I will check later and verify. There are some Spotify 404 errors I'm running into that I'm sure you're aware of (i.e. unable to view "Featured" and "Monitored" tabs), but they are unrelated to this issue.

**Comment by kamilkosek** [comment]
Yeah, currently the spotify API Seems to have some issues fetching playlists and several other stuff.

**Comment by NovaCyntax** [comment]
I'm going to close this, as it appears to be downloading songs correctly. The task hasn't completed yet (I created a large test suite of playlists), but the original error appears to be corrected. Great work!

**Comment by NovaCyntax** [comment]
On the latest dev build, it seems as if the download tasks on my end stop shortly after beginning (within a couple minutes). There is no error message displayed in the logs, everything appears to be normal in the log messages. Not sure if this would be related to the Spotify API deprecation or not.

**Comment by abjeroen** [comment]
thanks for the dev build. Download is working now, I had the same issue as above

**Comment by kamilkosek** [comment]
@NovaCyntax are you still encountering this issue ?

**Comment by NovaCyntax** [comment]
On the latest `dev` release, the download task immediately fails, but there are no logs generated. I will debug the issue more tonight when I can.
