### ISSUE TITLE
Playlists Removed From Jellyfin Cannot Be Re-Added

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#21]
When removing a Playlist from Jellyfin from within the Jellyplist UI, occasionally the playlist cannot be re-added. I have only tested this with Playlists that have not been 100% downloaded. Upon pressing the green plus-sign icon to add the Playlist to Jellyfin, the following message is present in the logs:

```
[2024-11-26 20:22:01,480] ERROR in app: Exception on /addplaylist [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'add_playlist' did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by kamilkosek** [comment]
Thanks, I’ll take a look into this tomorrow

**Comment by NovaCyntax** [comment]
This started working again sometime later. Not sure what was causing the issue, I encountered it 2 days in a row. Perhaps the updated image fixed it.
