### ISSUE TITLE
Download fails on timeout. Running SpotDL manually inside container hangs on Processing query: https://open.spotify.com/track/***trackid***

### ISSUE THREAD

**Issue by lavinir** [kamilkosek/jellyplist#22]
Hi,

I haven't been able to get the downloads to work. Logs show timeout failures on spotdl execution.
Manually trying to run this inside the container indeed seems to hang without any more logs (tried running spotdl with debug logging but nothing helpful after that line).

Any ideas what might be causing this?

**Comment by lavinir** [comment]
It's running inside a Proxmox LXC. I know it's probably not the recommended way but is there a reason this would cause such behavior ?

**Comment by kamilkosek** [comment]
Can you enable debug log and provide some logs from the worker ? 
Just add an additional env var 
```env
LOG_LEVEL = DEBUG
```
Then try to run the download task and post the logs from the worker container.
At the moment I am also facing some issues with the API from spotify.

**Comment by lavinir** [comment]
After updating (and trying to start fresh) I'm getting an Internal Server error trying to open the "Featured", "Monitored" and "Jellyfin Playlists" tabs.

Featured:
```
ERROR - HTTP Error for GET to https://api.spotify.com/v1/browse/featured-playlists with Params: {'locale': None, 'country': 'DE', 'timestamp': None, 'limit': 16, 'offset': 0} returned 404 due to Not Found
jellyplist           | [2024-11-28 07:53:42,204][            app.py: 875 -        log_exception() ]   ERROR - Exception on /playlists [GET]
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 275, in _internal_call
jellyplist           |     response.raise_for_status()
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
jellyplist           |     raise HTTPError(http_error_msg, response=self)
jellyplist           | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/browse/featured-playlists?country=DE&limit=16&offset=0
```

Not sure why it's using DE as the locale.

Jellyfin:
```
[2024-11-28 08:01:23,191][      functions.py:  49 -     prepPlaylistData() ]   ERROR - jellyfin_user not set: session user id: d5a752815617486a9f537940704c330b. Logout and Login again
jellyplist           | [2024-11-28 08:01:23,191][            app.py: 875 -        log_exception() ]   ERROR - Exception on /playlists/monitored [GET]
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
jellyplist           |     response = self.full_dispatch_request()
jellyplist           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
jellyplist           |     rv = self.handle_user_exception(e)
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
jellyplist           |     rv = self.dispatch_request()
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
jellyplist           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
jellyplist           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/functions.py", line 273, in decorated_function
jellyplist           |     return f(*args, **kwargs)
jellyplist           |            ^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/routes.py", line 170, in loaditems
jellyplist           |     next_offset = offset + len(data)
jellyplist           |                            ^^^^^^^^^
jellyplist           | TypeError: object of type 'NoneType' has no len()
```

**Comment by kamilkosek** [comment]
HI @lavinir 
the Locale is/was hardcoded, in the next release you can change it via env var to your prefered. 
The Errors in Featured, Monitored and overall fetching playlists details from `Algorithmic and Spotify-owned editorial playlists` are caused by recent API changes from spotify. See this issue #25 to get more insights and updates.

**Comment by kamilkosek** [comment]
Can you give it another try ? With the latest 0.1.8 there were a lot of issues fixed

**Comment by lavinir** [comment]
Thanks @kamilkosek. No longer getting the errors navigating the UI tabs but download still isn't working for me: (this is from executing the download task manually)

```
jellyplist           | [2024-12-07 13:09:10,661][            app.py: 875 -        log_exception() ]   ERROR - Exception on /run_task/download_missing_tracks [POST]
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
jellyplist           |     response = self.full_dispatch_request()
jellyplist-beat      | [2024-12-07 13:06:50,513][        spotify.py: 115 -  _fetch_client_token() ]   DEBUG - fetched granted_token
jellyplist           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
jellyplist           |     rv = self.handle_user_exception(e)
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
jellyplist           |     rv = self.dispatch_request()
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
jellyplist           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
jellyplist           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/functions.py", line 176, in decorated_function
jellyplist           |     return f(*args, **kwargs)
jellyplist           |            ^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/routes/routes.py", line 115, in run_task
jellyplist           |     status, info = tasks.task_manager.start_task(task_name)
jellyplist           |     ^^^^^^^^^^^^
jellyplist           | ValueError: too many values to unpack (expected 2
```

**Comment by lavinir** [comment]
Working now, Thanks!
