### ISSUE TITLE
[Possible Breaking Change] Existing Database Does Not Migrate Cleanly

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#29]
Great work on the new release! I believe I got it set up correctly and am looking forward to testing it out. When I initially attempted migrating to the new update, I kept running into errors regarding database columns and values. The solution for me was to delete my existing postgres and redis_data volumes. I didn't have anything important in there, so it wasn't a problem for me.

Some error logs I noted prior to resolving:

```
2024-12-05 01:01:31.315 UTC [206] ERROR:  column "provider_playlist_id" of relation "playlist" contains null values
INFO  [alembic.runtime.migration] Running upgrade d4fef99d5d3c -> 18d056f49f59, refacotring db to work with multiple music provider
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "provider_playlist_id" of relation "playlist" contains null values
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
    cli.main()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 400, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_migrate/cli.py", line 154, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/jellyplist/migrations/env.py", line 113, in <module>
    run_migrations_online()
  File "/jellyplist/migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/jellyplist/migrations/versions/18d056f49f59_refacotring_db_to_work_with_multiple_.py", line 21, in upgrade
    with op.batch_alter_table('playlist', schema=None) as batch_op:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.12/site-packages/alembic/operations/base.py", line 398, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.12/site-packages/alembic/operations/batch.py", line 116, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.12/site-packages/alembic/ddl/impl.py", line 337, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.12/site-packages/alembic/ddl/impl.py", line 210, in _exec
    return conn.execute(construct, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "provider_playlist_id" of relation "playlist" contains null values
[SQL: ALTER TABLE playlist ADD COLUMN provider_playlist_id VARCHAR(120) NOT NULL]
```

**Comment by kamilkosek** [comment]
Hi, thanks for reaching out again. 
Obviously I made a mistake renaming the columns and not pointing out to drop the existing postgres data or providing a reasonable migration script.

**Comment by mappers653** [comment]
what am I doing wrong, I understand this was fixed, running latest dev
```dockerfile
INFO  [alembic.runtime.migration] Running upgrade d4fef99d5d3c -> 18d056f49f59, refacotring db to work with multiple music provider
postgres-jellyplist  | 2024-12-08 20:33:58.214 UTC [1797] ERROR:  column "provider_playlist_id" of relation "playlist" contains null values
postgres-jellyplist  | 2024-12-08 20:33:58.214 UTC [1797] STATEMENT:  ALTER TABLE playlist ADD COLUMN provider_playlist_id VARCHAR(120) NOT NULL
jellyplist-beat      | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
jellyplist-beat      | INFO  [alembic.runtime.migration] Will assume transactional DDL.
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
jellyplist           |     self.dialect.do_execute(
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
jellyplist           |     cursor.execute(statement, parameters)
jellyplist           | psycopg2.errors.NotNullViolation: column "provider_playlist_id" of relation "playlist" contains null values
jellyplist           | 
jellyplist           | 
jellyplist           | The above exception was the direct cause of the following exception:
```

**Comment by NovaCyntax** [comment]
My solution was stopping all containers, and running `rm -r postgres` and `rm -r redis_data`

I then restarted the containers and it worked fine. I had to re-add all my playlists, but that wasn't a problem for me. If you want to keep your current data, I'm not sure what to recommend

**Comment by mappers653** [comment]
worked

**Comment by kamilkosek** [comment]
I will close this one for now.
