### ISSUE TITLE
download_missing_tracks results in FAILURE (KeyError: 'output' and ValueError: too many values to unpack (expected 2)))

### ISSUE THREAD

**Issue by Master449** [kamilkosek/jellyplist#30]
Credentials should be fine in my `.env` as they worked on the last version. I did update the cookies.txt file for both youtube and spotify, and also tried it without the youtube music one. Unsure if it was still needed or not, as its not in the instructions, but its in the docker compose file.

If it matters at all: I had issues with the database migrations from the previous version, so this should be a clean build, as both postgres and redis directories were recreated.

Running NixOS 24.04 (Kernel 6.6.53)

```
jellyplist-worker    | [2024-12-05 02:53:40,035][       strategy.py: 161 -    task_message_handler() ]    INFO - Task app.tasks.download_missing_tracks[308734d7-9460-4152-9f6c-ee9476d50e88] received
jellyplist           | [2024-12-05 02:53:40,035][            app.py: 875 -        log_exception() ]   ERROR - Exception on /run_task/download_missing_tracks [POST]
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
jellyplist           |     response = self.full_dispatch_request()
jellyplist           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
jellyplist           |     rv = self.handle_user_exception(e)
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
jellyplist           |     rv = self.dispatch_request()
jellyplist           |          ^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
jellyplist           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
jellyplist           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/functions.py", line 176, in decorated_function
jellyplist           |     return f(*args, **kwargs)
jellyplist           |            ^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/app/routes/routes.py", line 115, in run_task
jellyplist           |     status, info = tasks.task_manager.start_task(task_name)
jellyplist           |     ^^^^^^^^^^^^
jellyplist           | ValueError: too many values to unpack (expected 2)
jellyplist-worker    | [2024-12-05 02:53:40,037][          tasks.py: 110 - download_missing_tracks() ]    INFO - Starting track download job...
jellyplist-worker    | [2024-12-05 02:53:40,040][          trace.py: 267 -              _log_error() ]   ERROR - Task app.tasks.download_missing_tracks[308734d7-9460-4152-9f6c-ee9476d50e88] raised unexpected: KeyError('output')
jellyplist-worker    | Traceback (most recent call last):
jellyplist-worker    |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
jellyplist-worker    |     R = retval = fun(*args, **kwargs)
jellyplist-worker    |                  ^^^^^^^^^^^^^^^^^^^^
jellyplist-worker    |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
jellyplist-worker    |     return self.run(*args, **kwargs)
jellyplist-worker    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist-worker    |   File "/jellyplist/app/tasks.py", line 115, in download_missing_tracks
jellyplist-worker    |     output_dir = spotdl_config['output']
jellyplist-worker    |                  ~~~~~~~~~~~~~^^^^^^^^^^
jellyplist-worker    | KeyError: 'output'
```

**Comment by NovaCyntax** [comment]
I've been debugging this for the past hour or so to see if it was an issue on my end. Glad I'm not the only one, same behavior and logs. I will dig a bit more and see if I find anything

**Comment by chrisbehectik** [comment]
I'm running into same. I even think the the log output is exactly the same. Also clean build for the same reason of database migrations issues.

**Comment by kamilkosek** [comment]
Sh** , sorry guys for wasting your time. Must have missed this, because it was too  late.
Apparently Python returns an array of strings when joining a path. Will fix this asap and push a release today

**Comment by NovaCyntax** [comment]
No problem, your work is going to save a lot of people a lot of time! I enjoy the testing process and watching this come together has been exciting, as I've long needed something like this.

**Comment by serghidalg** [comment]
I was doing all this scripting by hand and your tool is just too damn good!
Looking forward for the fix and thank you for your amazing work!!

**Comment by Master449** [comment]
Appreciate it!
