### ISSUE TITLE
[BUG] Deleting playlist from Jellyfin breaks "/jellyplist_playlists" page

### ISSUE THREAD

**Issue by chrisbehectik** [kamilkosek/jellyplist#33]
I want to preface this with a huge thank you for your work! This app amazing and is something I've been looking around for for such a long time!

It seems that deleting a playlist created by jellyplist from Jellyfin breaks jellyplist playlists page: 

How to replicate:
1. Go to Music library in Jellyfin.
2. Go to Playlists tab.
3. Select 3 dots button on playlist.
4. Select Delete.
5. Select Delete.
6. Go to  http://<IP>:5055/jellyfin_playlists
7. Get below error:
![image](https://github.com/user-attachments/assets/496d2af9-627c-4bbb-9284-db71a4bb4b1f)

Trying to re-add the playlist also fails with an error:
![image](https://github.com/user-attachments/assets/dbe27340-0098-46a3-8c38-17030e280784)

Let me know if you need logs and from which container.

**Comment by kamilkosek** [comment]
I will try to reproduce this at my site and push a fix for this today.

**Comment by mrxorao** [comment]
![msedge_xCSX4ywbc9](https://github.com/user-attachments/assets/b6e22591-909d-4b61-b512-a7336bb128b8)

- There is no option to delete the playlist,
- when I click to add it, it gives this error “Unsupported image format: image/webp”

But it's already been added in jellyfin

![image](https://github.com/user-attachments/assets/b0e1928a-0ae3-4ae2-8a0d-c6bde556c15e)

**Comment by kamilkosek** [comment]
Hm... somehow I am unable to reproduce this. 
Are anyone of you willing to provide some logs from the main app ? 
Please enable debug mode and feel free to post everything.

**Comment by mrxorao** [comment]
> ![msedge_xCSX4ywbc9](https://private-user-images.githubusercontent.com/154644247/393231184-b6e22591-909d-4b61-b512-a7336bb128b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODY5MDgsIm5iZiI6MTczMzQ4NjYwOCwicGF0aCI6Ii8xNTQ2NDQyNDcvMzkzMjMxMTg0LWI2ZTIyNTkxLTkwOWQtNGI2MS1iNTEyLWE3MzM2YmIxMjhiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDFmOWIzZGYxYWU2MzgwZmFkNzk1NjRmMGU3NDdjMGI3MjBkOGUyY2RjZGVlZmQ1ZTBkMzZlYzc2ODdiODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PvbCXeuF-YaZfPvTdF_uQyHwPd2BQpcWLXr0cVlEW1Q)
> 
> * There is no option to delete the playlist,
> * when I click to add it, it gives this error “Unsupported image format: image/webp”
> 
> But it's already been added in jellyfin
> 
> ![image](https://private-user-images.githubusercontent.com/154644247/393232076-b0e1928a-0ae3-4ae2-8a0d-c6bde556c15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODY5MDgsIm5iZiI6MTczMzQ4NjYwOCwicGF0aCI6Ii8xNTQ2NDQyNDcvMzkzMjMyMDc2LWIwZTE5MjhhLTBhZTMtNGFlMi04YTBkLWM2YmRlNTU2YzE1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTkzZTNmYTdkZDdjZDdhY2MyMGNhM2NkMTA4ZDE3M2UwNzhlYTk4MDYxMDQwNTk0MGYwZmExNTVmYTcwZjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GNb30-5-tAz2boItty5sHtglX94Yktj64ozXPWXzIu4)

[2024-12-06 12:08:48,953][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+0%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:08:49,142][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+50%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:08:49,367][         client.py: 126 - get_playlist_metadata() ]   DEBUG - Url=http://localhost:9999/Items/1648ceb3344535b091c98863a546d92a
[2024-12-06 12:08:49,524][         client.py: 129 - get_playlist_metadata() ]   DEBUG - Response = 200
[2024-12-06 12:08:49,524][         client.py: 161 - update_playlist_metadata() ]   DEBUG - Url=http://localhost:9999/Items/1648ceb3344535b091c98863a546d92a
[2024-12-06 12:08:49,711][         client.py: 164 - update_playlist_metadata() ]   DEBUG - Response = 204
[2024-12-06 12:09:17,702][       __init__.py:  12 -  set_active_provider() ]   DEBUG - Setting active provider: Spotify
[2024-12-06 12:09:17,703][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+0%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:09:17,861][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+50%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:09:18,041][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A37i9dQZEVXbMDoHDwVN2tF%22%2C+%22offset%22%3A+0%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:09:23,158][       __init__.py:  12 -  set_active_provider() ]   DEBUG - Setting active provider: Spotify
[2024-12-06 12:09:23,159][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+0%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:09:23,359][        spotify.py: 128 -        _make_request() ]   DEBUG - starting request: https://api-partner.spotify.com/pathfinder/v1/query?operationName=fetchPlaylist&variables=%7B%22uri%22%3A+%22spotify%3Aplaylist%3A0KE6Iqq39fdtsDGaXMemk2%22%2C+%22offset%22%3A+50%2C+%22limit%22%3A+50%7D&extensions=%7B%22persistedQuery%22%3A+%7B%22version%22%3A+1%2C+%22sha256Hash%22%3A+%2219ff1327c29e99c208c86d7a9d8f1929cfdf3d3202a0ff4253c821f1901aa94d%22%7D%7D
[2024-12-06 12:09:23,525][         client.py: 126 - get_playlist_metadata() ]   DEBUG - Url=http://localhost:9999/Items/1648ceb3344535b091c98863a546d92a
[2024-12-06 12:09:23,554][         client.py: 129 - get_playlist_metadata() ]   DEBUG - Response = 200
[2024-12-06 12:09:23,555][         client.py: 161 - update_playlist_metadata() ]   DEBUG - Url=http://localhost:9999/Items/1648ceb3344535b091c98863a546d92a
[2024-12-06 12:09:23,589][         client.py: 164 - update_playlist_metadata() ]   DEBUG - Response = 204

**Comment by chrisbehectik** [comment]
> Hm... somehow I am unable to reproduce this. Are anyone of you willing to provide some logs from the main app ? Please enable debug mode and feel free to post everything.

Logs from the app container when trying to reach the "/jellyfin_playlists" page:

```
[2024-12-06 12:11:46,932][            app.py: 875 -        log_exception() ]   ERROR - Exception on /jellyfin_playlists [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/functions.py", line 167, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/routes/jellyfin_routes.py", line 17, in jellyfin_playlists
    playlists = jellyfin.get_playlists(session_token=functions._get_token_from_sessioncookie())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/jellyfin/client.py", line 192, in get_playlists
    raise Exception(f"Failed to get playlists: {response.content}")
Exception: Failed to get playlists: b''
```

**Comment by kamilkosek** [comment]
@chrisbehectik no need to feel silly 👍 
I got several takeaways from this:

- [ ] When Authentication with the Jellyfin Server fails (for whatever reason .. which I need to find out 😢 ) , the user needs to be prompted with a message, logged out and redirected to the login 
- [ ] Rework the jellyfin api client to make better use of the status codes and provide the user more feedback
- [ ] Rework the jellyfin api client to make more verbose logs when exceptions are thrown 
- [ ] Provide a feature to open an issue directly at GitHub with automatically provided logs 🤔 💭

**Comment by chrisbehectik** [comment]
> Trying to re-add the playlist also fails with an error: ![image](https://private-user-images.githubusercontent.com/139649834/393197494-dbe27340-0098-46a3-8c38-17030e280784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODgyNzIsIm5iZiI6MTczMzQ4Nzk3MiwicGF0aCI6Ii8xMzk2NDk4MzQvMzkzMTk3NDk0LWRiZTI3MzQwLTAwOTgtNDZhMy04YzM4LTE3MDMwZTI4MDc4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMjI2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmY3ZTcyY2YzZjFmZmU3MWEwOWExOGM2MzU0ZDMyZWI0Y2RkNzUwNzA4ZjhiNWQ1NDAyMWE3ZTc0MThmMjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BegP5a701-fgJCZlo4CaHjKLBNMEgbQMosvsKjFQOKw)

This is still an issue when re-adding. Unlike the `image/webp` error which stills adds the playlist this error does not add the playlist to jellyfin or the "/jellyfin_playlists" in jellyplist page.

Nothing in the app container logs referring to this error.

**Comment by kamilkosek** [comment]
Ok i See, and after log out and log in it works again ?

**Comment by chrisbehectik** [comment]
Even after logging out and in again I'm not able to re-add the playlist that I manually deleted in Jellyfin.

**Comment by NovaCyntax** [comment]
For what it's worth, I've had this issue has well, but assumed it was due to stress-testing. I don't have a log capture at the moment, but I do have playlists which are in Jellyfin but the "add/remove" buttons in Jellyplist aren't in an accurate state. I haven't played around with the issue enough to see what causes it.
