### ISSUE TITLE
Lidarr Task "Too Many Values to Unpack"

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#38]
I ran the Lidarr task from the admin page out of curiosity, and encountered this error. I'm not sure if another task was in process while I ran it. I'm actually not even sure what the Lidarr task does at the moment, so I just tried it to see. My Lidarr instance is connected correctly as I'm able to see my Quality Profiles listed within Jellyfin.

```
[2024-12-07 05:48:17,861][            app.py: 875 -        log_exception() ]   ERROR - Exception on /run_task/request_lidarr [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/functions.py", line 176, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/routes/routes.py", line 115, in run_task
    status, info = tasks.task_manager.start_task(task_name)
    ^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by kamilkosek** [comment]
Basically, the task just sets an album or artist as monitored.
Will take a look at this one
