### ISSUE TITLE
Error 400 when request_lidarr

### ISSUE THREAD

**Issue by gdshadow01** [kamilkosek/jellyplist#59]
Hi and thanks for your awesom work! 

Requesting albums from lidarr from admin panel fails for me. Here is a snipped of the log output. That happens for every album. I'm using latest release and did a full new setup in case I missed a change.  

`jellyplist           | [2024-12-16 12:18:35,479][      functions.py: 267 -                        set_log_level() ]    INFO - Log level set to DEBUG
jellyplist           | [2024-12-16 12:18:47,197][          tasks.py: 493 -                             request_lidarr() ]    INFO - Submitting request to Lidarr...
jellyplist           | [2024-12-16 12:18:47,434][          tasks.py: 553 -                             request_lidarr() ]   ERROR - Error monitoring album SOMEALBUMTITLE: 400 Client Error: Bad Request for url: http://xxx.xxx.x.xxx:8686/api/v1/album
jellyplist           | [2024-12-16 12:18:47,437][          tasks.py: 553 -                             request_lidarr() ]   ERROR - Error monitoring album SOMEALBUMTITLE: 400 Client Error: Bad Request for url: http://xxx.xxx.x.xxx:8686/api/v1/album/21272
jellyplist           | [2024-12-16 12:18:47,616][          tasks.py: 553 -                             request_lidarr() ]   ERROR - Error monitoring album OTHERALBUMTITLE: 400 Client Error: Bad Request for url: http://xxx.xxx.x.xxx:8686/api/v1/album/686
`

There is another error in the logs, I don't know if it is related:

`jellyplist           | [2024-12-16 12:25:00,355][          tasks.py:  98 -          update_all_playlists_track_status() ]   ERROR - Error downloading tracks: Failed to get item: b'{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.5","title":"Not Found","status":404,"traceId":"00-198261658252ca9033a81dfab09bb0c8-1e2a1fe174b7c669-00"}'
jellyplist           | Traceback (most recent call last):
jellyplist           |   File "/jellyplist/app/tasks.py", line 63, in update_all_playlists_track_status
jellyplist           |     jellyfin_track = jellyfin.get_item(jellyfin_admin_token, track.jellyfin_id)
jellyplist           |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jellyplist           |   File "/jellyplist/jellyfin/client.py", line 328, in get_item
jellyplist           |     raise Exception(f"Failed to get item: {response.content}")
jellyplist           | Exception: Failed to get item: b'{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.5","title":"Not Found","status":404,"traceId":"00-198261658252ca9033a81dfab09bb0c8-1e2a1fe174b7c669-00"}'
jellyplist           | [2024-12-16 12:25:00,522][          tasks.py: 326 -                 check_for_playlist_updates() ]    INFO - Checking updates for playlist: Test
`

**Comment by kamilkosek** [comment]
Hi, 
I will try to find what´s the cause of this issue is.

**Comment by gdshadow01** [comment]
Thank you!
A quick and dirty workaround in the meantime if someone needs it: set lidarr root folder to monitor  existing albums. The albums will get picked up by sonarr on rescan.

**Comment by BitlessByte0** [comment]
I would like to add that I am also experiencing this issue. Willing to help debug by providing logs if that will help.
